#' Example eDNA metabarcoding dataset
#'
#' @description
#' A simulated eDNA metabarcoding dataset generated by the package's own
#' simulation pipeline ([simulate_eDNA_survey()]). The dataset has known
#' ground-truth community structure (K = 4 communities) separated by depth
#' and distance from shore. Use it to learn the package, follow the tutorial
#' (`vignette("tutorial")`), and verify your installation.
#'
#' Load it via [get_example_data()].
#'
#' @format A named list (the output of [simulate_eDNA_survey()]) with elements:
#' \describe{
#'   \item{`counts`}{Integer matrix (20 samples × 40 taxa). Rows are stations
#'     (`STN_001`–`STN_020`), columns are species (`Sp_1`–`Sp_40`).}
#'   \item{`covariates`}{Data frame (20 rows): `sample_id`, `TrueCommunity`,
#'     `Depth` (m), `Distance_shore` (arbitrary units).}
#'   \item{`community_compositions`}{True [4 × 40] composition matrix.}
#'   \item{`metab_df`}{Raw metabarcoding data frame from the simulation.}
#'   \item{`sample_metadata`}{Full simulation metadata.}
#'   \item{`contributors`}{Contributor simulation output.}
#' }
#'
#' @section Community structure:
#' Four communities separated by two covariates:
#' \itemize{
#'   \item **Community 1**: deep (80 m) + offshore (200 units)
#'   \item **Community 2**: surface (10 m) + offshore (200 units)
#'   \item **Community 3**: deep (80 m) + inshore (20 units)
#'   \item **Community 4**: surface (10 m) + inshore (20 units)
#' }
#' Spillover = 0.15 (15% of frequency leaks between communities).
#' Overdispersion alpha = ~3.
#'
#' @source Generated by `simulate_eDNA_survey()` with `seed = 2026`.
#'   See `data-raw/generate_example_data.R` for the exact call.
#'
#' @examples
#' data <- get_example_data()
#' dim(data$counts)          # 20 x 40
#' head(data$covariates)
#'
#' @name example_edna
#' @docType data
#' @keywords datasets
NULL
